on: 
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Start server
        run: npm run start:server &
      - name: Build and deploy to github pages
        run: |
          npm run build
          git checkout -b gh-pages
          git add .
          git add dist/*
          git commit -m "Deploy to github pages with latest changes"
          git push origin gh-pages



